### ISSUE TITLE
[API] The `NAME_VENV` var is never used

### ISSUE THREAD

**Issue by LexABzH** [OSS-Pole-Emploi/gabarit#137]
### Describe the bug

The `NAME_VENV` var is never used in the API's Makefile file.

## Concerned template

  - [ ] NLP template
  - [ ] NUM template
  - [ ] VISION template
  - [x] API template
  - [ ] How templates are generated - Jinja

### Expected behavior

It should be used in `create-virtualenv`.

### Actual behavior

It is not used.

### Is this a regression?

That is, did this use to work the way you expected in the past?

- [ ] Yes
- [x] No

### Debug info

- Gabarit version: latest
- Python version: any
- OS version: any

**Comment by gsolard** [comment]
Closed with PR  #149
